---
- name: Clone the geonotebook repository
  git:
    repo: https://github.com/OpenGeoscience/geonotebook.git
    dest: "{{ geonotebook_dir }}"
    version: "{{ geonotebook_version }}"
    accept_hostkey: yes

- name: Install system dependencies
  apt:
    name: "{{ item }}"
  with_items:
    - gdal-bin
    - python-numpy
    - python-matplotlib
    - libgdal-dev
    - python-numpy
    - python-matplotlib
    - python-gdal
    - python-matplotlib
    - python-numpy
    - python-pip
    - python-rasterio
    - python-requests

- name: Update pip and install example notebook requirements
  pip:
    executable: pip2
    name: "pip"
    state: latest
    chdir: "{{ geonotebook_dir }}"

- name: Use system installed python-gdal
  lineinfile:
    line: "GDAL==1.11.2"
    state: absent
    dest: "{{geonotebook_dir}}/requirements.txt"
  when: use_system_python_gdal is defined

- name: Install geonotebook python requirements
  pip:
    executable: pip2
    requirements: "{{geonotebook_dir}}/requirements.txt"
  environment:
    CPLUS_INCLUDE_PATH: /usr/include/gdal
    C_INCLUDE_PATH: /usr/include/gdal

- name: Install the geonotebook package
  pip:
    executable: pip2
    extra_args: "-e"
    name: "."
    state: latest
    chdir: "{{ geonotebook_dir }}"

- name: Template out the geonotebook.ini configuration file
  template:
    src: geonotebook.ini.j2
    dest: /usr/local/etc/geonotebook.ini
