---
- name: Clone the geonotebook repository
  git:
    repo: https://github.com/OpenGeoscience/geonotebook.git
    dest: "{{ geonotebook_dir }}"
    version: "{{ geonotebook_version }}"
    accept_hostkey: yes

- name: Install system dependencies
  apt:
    name: "{{ item }}"
  with_items:
    - gdal-bin
    - python-numpy
    - python-matplotlib
    - python-seaborn
    - libgdal-dev
    - python-numpy
    - python-matplotlib
    - python-gdal
    - python-matplotlib
    - python-numpy
    - python-pip
    - python-rasterio
    - python-requests
    - python-skimage
    - python3-gdal
    - python3-matplotlib
    - python3-numpy
    - python3-pip
    - python3-rasterio
    - python3-requests
    - python3-skimage

- name: Update pip and install ipywidgets
  pip:
    executable: pip2
    name: "{{ item }}"
    state: latest
    chdir: "{{ geonotebook_dir }}"
  with_items:
    - pip
    - ipywidgets

- name: Update pip and install ipywidgets
  pip:
    executable: pip3
    name: "{{ item }}"
    state: latest
    chdir: "{{ geonotebook_dir }}"
  with_items:
    - pip
    - ipywidgets

- name: Use system installed python-gdal
  lineinfile:
    line: "GDAL==1.11.2"
    state: absent
    dest: "{{geonotebook_dir}}/requirements.txt"
  when: use_system_python_gdal is defined


- name: Install geonotebook python requirements
  pip:
    executable: "{{ item }}"
    requirements: "{{geonotebook_dir}}/requirements.txt"
  with_items:
    - pip2
    - pip3

- name: Install the geonotebook package
  pip:
    executable: "{{ item }}"
    name: "."
    state: latest
    chdir: "{{ geonotebook_dir }}"
  with_items:
    - pip2
    - pip3

- name: Template out the geonotebook.ini configuration file
  template:
    src: geonotebook.ini.j2
    dest: /usr/local/etc/geonotebook.ini
