- hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars:
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
#  roles:
#    - role: ec2

  post_tasks:
    - name: Register the instance to dynamic inventory
      ec2_remote_facts:
        filters:
          instance-state-name: 'running'
          "tag:Name": "{{ ec2_instance_name }}"
        region: "{{ ec2_region }}"
      register: ec2

    - name: Add new instance to jupyterhub & geoserver groups
      add_host:
        hostname: "{{ item.public_dns_name }}"
        groups: "jupyter,geoserver"
        ansible_ssh_private_key_file: "{{ ec2_keypair_path }}"
        ansible_ssh_user: "{{ ansible_default_user }}"
#        ansible_python_interpreter: python3
      with_items: '{{ec2.instances}}'


# Handle installing python 2.7.11 on 16.04
- hosts: geoserver
  gather_facts: false
  tasks:
  - name: Install python2
    raw: >-
      sudo apt-get update && sudo apt-get install -y python

- include: geoserver/deploy.yml
